server:
  port: 8088
spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/themapisto/spring-cloud-config-repository


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # 유레카 서비스에 (자신을) 등록 여부
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka.taskoo.net/eureka