apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  namespace: springboot
  labels:
    app: config_server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config_server
  template:
    metadata:
      labels:
        app: config_server
    spec:
      containers:
      - name: config
        image: harbor.aikoo.net/tanzu/config:1.1
        ports:
        - containerPort: 8088

