apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: config
  name: config
  namespace: springboot
spec:
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: config
  type: ClusterIP
status:
  loadBalancer: {}
