apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: config
  namespace: springboot
spec:
  virtualhost:
    fqdn: config.taskoo.net
  routes:
    - services:
      - name: config
        port: 8088
